### ISSUE TITLE
TypeScript/Deno starter snake

### ISSUE THREAD

**Issue by tyrelh** [BattlesnakeOfficial/docs#1]
I have created a starter snake using TypeScript and [Deno](https://deno.land/).

It includes documentation to run locally using ngrok as well as deployment to Heroku. Also includes basic tests with instructions.

So far using Deno has been super simple and would be a great option for someone wanting to get started with Battlesnake using TypeScript.

I hope it can be included on the [Starter Projects](https://docs.battlesnake.com/references/starter-projects) page.

[TypeScript Starter Snake with Deno](https://github.com/tyrelh/starter-snake-typescript-deno) by [Tyrel Hiebert](https://github.com/tyrelh)

Thanks!

**Comment by bvanvugt** [comment]
@tyrelh this is great! A few notes, and we'll get it added to the Starter Projects page.
* can you update the link in the repo description to be play.battlesnake.com instead of www.battlesnake.com
* you've used "Cell" where we'd typically use "Coordinates". Cell is fine but it might not line up with docs as they evolve
* root.author default is <YOUR_GITHUB_USERNAME>, should be <YOUR_BATTLESNAKE_USERNAME> (which defaults to GitHub on registration)

**Comment by tyrelh** [comment]
Great! I've made those three changes

**Comment by bvanvugt** [comment]
Thanks! Added to listed projects here:
https://github.com/BattlesnakeOfficial/docs/commit/1277d42530de3205467d6aeb747fdf3ffe471f73
